
/**
 * @project OpenHoop
 * @file FractalPatternImage.cpp
 * @brief Source file for the FractalPatternImage class.
 * @details Implements methods to set colors for the POV image.
 * @author Automatically generated by github.com/angelcamelot/OpenHoopPOVImageBuilder
 * @date 2024-04-09
 * @license Open-source license.
 */

#ifndef OPENHOOP_FRACTALPATTERNIMAGE_H
#define OPENHOOP_FRACTALPATTERNIMAGE_H

#include "POVImage.h"

/**
 * @brief Represents an image of POV Image for the Hula Hoop LED display.
 */
class Fractalpatternimage : public POVImage {
public:
    /**
     * @brief Constructor for the Fractalpatternimage class.
     */
    explicit Fractalpatternimage();

private:
    /**
     * @brief Set the colors for the FractalPatternImage.
     */
    void setColors();
};

#endif //OPENHOOP_FRACTALPATTERNIMAGE_H

        